"""Dr. Elaine Ingham, "How to Build Great Soil, Part 1" (Diego Footer): the November and December 2026 post series.

python3 build_elaine_series.py            -> every post
python3 build_elaine_series.py pizza ...  -> only the named posts (keys of POSTS at the bottom)

Clean template set in the spirit of the template specs (1B quote, 2 myth-buster, 3 checklist, 5 big number,
6 reel cover and caption cards, 7 story), brand palette from docs/brand-colors.md, Legacy Purple only on quote slides.
Collage pieces: assets/collage/cutouts/ (tools/collage_generate.py, flux-2-pro with style-reference.png), placed
straight, never tilted. Slide text is the brief's Words section, word for word. Every element is editable.
"""
import os, sys
from PIL import Image
from pptx.util import Emu, Pt

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "october"))
from lib import Deck, rect, text, crop, est_lines, _place, ROOT, PX, HEAD, BODY, rgb   # noqa: E402

GREEN, DARK, CREAM, BROWN, SAGE, TAN, INK = "31662F", "1E3F1D", "F3F1EA", "4C3634", "B1BCB1", "C09D7F", "333130"
PURPLE, GLOW, FAINT, TODO = "6B4C7A", "DBE6A7", "6A665C", "B23A2E"
GARA = "EB Garamond"
CUT = "assets/collage/cutouts/"
MIC = "assets/microscopy/"
LOGO_COLOR, LOGO_WHITE = "assets/logo/foundation-logo-color.png", "assets/logo/foundation-logo-white.png"
TMP = os.path.join(ROOT, "renders", ".tmp")
VIDEO = "https://www.youtube.com/watch?v=ErMHR6Mc4Bk"
CREDIT = 'Dr. Elaine Ingham, "How to Build Great Soil, Part 1", Diego Footer'
SERIES = "DR. ELAINE INGHAM · HOW TO BUILD GREAT SOIL"
CLARHOLM = ('Clarholm, "Interactions of bacteria, protozoa and plants leading to mineralization of soil nitrogen", Soil Biology '
            "and Biochemistry, 1985: https://scholar.google.com/scholar?q=Clarholm+1985+Interactions+of+bacteria+protozoa+and+"
            "plants+leading+to+mineralization+of+soil+nitrogen")
RULES = ("Credit line for every quote: " + CREDIT + ". Short quotes with credit are fine; video clips and long excerpts "
         "need Evan to check with Diego first. Caption needs review by Allison (AI-generated by Linnea).")
MISSING = []
PREVIEW = "--preview" in sys.argv     # caption cards on Deep Green, for the review render only


def ts(t):
    m, s = t.split(":"); return f"{VIDEO}&t={int(m) * 60 + int(s)}s"


def src(*times):
    return "Sources: " + "; ".join(f"{CREDIT}, {t}: {ts(t)}" for t in times) + "."


# ---------------------------------------------------------------- pieces
def picture(s, path, x, y, w, h):
    sh = s.shapes.add_picture(path, Emu(int(x * PX)), Emu(int(y * PX)), Emu(int(w * PX)), Emu(int(h * PX)))
    return sh


def logo(s, x, y, w, white):
    return picture(s, os.path.join(ROOT, LOGO_WHITE if white else LOGO_COLOR), x, y, w, w * 668 / 743)


def trimmed(rel):
    os.makedirs(TMP, exist_ok=True)
    out = os.path.join(TMP, "trim-" + os.path.basename(rel))
    im = Image.open(os.path.join(ROOT, rel)).convert("RGBA")
    box = im.split()[3].point(lambda v: 255 if v > 20 else 0).getbbox()
    im.crop(box).save(out)
    return out


def art(s, rel, x, y, w, h):
    """Cutout (collage or microscopy) fitted inside the box, centred, straight. Placeholder if it does not exist."""
    if not os.path.exists(os.path.join(ROOT, rel)):
        MISSING.append(rel)
        return placeholder(s, x, y, w, h, "COLLAGE: " + os.path.basename(rel))
    p = trimmed(rel); iw, ih = Image.open(p).size; r = min(w / iw, h / ih)
    return picture(s, p, x + (w - iw * r) / 2, y + (h - ih * r) / 2, iw * r, ih * r)


def photo(s, rel, x, y, w, h, fx=0.5, fy=0.5):
    if not rel or not os.path.exists(os.path.join(ROOT, rel)):
        return placeholder(s, x, y, w, h, "PHOTO: " + (rel or "needed"))
    return picture(s, crop(rel, int(w), int(h), fx, fy), x, y, w, h)


def placeholder(s, x, y, w, h, label):
    rect(s, x, y, w, h, "D9D4C7")
    text(s, x + 30, y, w - 60, h, label, 24, "4A463F", HEAD, True, align="c", anchor="m")
    MISSING.append(label)


from PIL import ImageFont
FONTFILE = {(HEAD, True): "~/.fonts/Montserrat-Bold.ttf", (BODY, False): "~/.fonts/SourceSans3-Regular.ttf",
            (GARA, False): "~/.fonts/EBGaramond-Italic.ttf"}
_F = {}


def nlines(t, pt, w, font, bold):
    """Real line count, measured with the font files (emoji measured as one wide glyph)."""
    k = (font, bold, pt)
    if k not in _F: _F[k] = ImageFont.truetype(os.path.expanduser(FONTFILE[(font, bold)]), int(pt * 1.3333))
    f = _F[k]; n = 0
    for para in t.split("\n"):
        n += 1; cur = ""
        for word in para.split(" "):
            trial = (cur + " " + word).strip()
            if cur and f.getlength(trial) > w * 0.97: n += 1; cur = word
            else: cur = trial
    return n


def fit(t, w, h, sizes, font=HEAD, bold=True, sp=1.12):
    for pt in sizes:
        hh = nlines(t, pt, w, font, bold) * pt * 1.3333 * 1.17 * sp
        if hh <= h: return pt, hh
    pt = sizes[-1]; return pt, nlines(t, pt, w, font, bold) * pt * 1.3333 * 1.17 * sp


def words(s, t, x, y, w, h, color=INK, sizes=(56, 52, 48, 44, 40, 36, 32), font=HEAD, bold=True, anchor="t", sp=1.12, italic=False):
    pt, th_ = fit(t, w, h, sizes, font, bold, sp)
    yy = y + (h - th_) / 2 if anchor == "m" else y
    text(s, x, yy, w, th_ + 20, t, pt, color, font, bold, italic=italic, spacing=sp)
    return yy + th_


# ---------------------------------------------------------------- slide furniture
class Post:
    def __init__(self, name, folder="november", w=1080, h=1350):
        self.name, self.folder, self.W, self.H = name, folder, w, h
        self.d = Deck(w, h, name=name)

    def slide(self, bg, note):
        return self.d.slide(bg, note + " " + RULES, counter=False)

    def save(self):
        path = os.path.join(ROOT, "templates", "posts", self.folder, self.name + ".pptx")
        if PREVIEW: path = os.path.join(TMP, "preview", self.folder, self.name + ".pptx")
        self.d.finish(path, counters=False)
        print("wrote", os.path.relpath(path, ROOT))
        return path


def furniture(p, s, dark, first=False, last=False, source=None, series=True):
    """Series label top left; source line bottom left; logo on the first and last slide, soilfoodweb.com otherwise."""
    W, H = p.W, p.H
    fg = CREAM if dark else GREEN
    if series:
        text(s, 80, 70, W - 160, 30, SERIES, 18, GLOW if dark else GREEN, HEAD, True, track=2)
    if source:
        text(s, 80, H - 92, W - 80 - 80 - 300, 50, source, 16, CREAM if dark else FAINT, BODY, alpha=80 if dark else None, spacing=1.05)
    if first or last:
        logo(s, W - 80 - 110, H - 70 - 110 * 668 / 743, 110, white=dark)
    else:
        text(s, W - 80 - 260, H - 88, 260, 30, "soilfoodweb.com", 18, fg, HEAD, True, align="r")


def t3(p, t, rel=None, note="", source=None, first=False, last=False, step=None, photo_rel=None, img_h=560, focus=(0.5, 0.5)):
    """Template 3 item: words on cream, then the picture. Optional big step number."""
    s = p.slide(CREAM, "Template 3. " + note)
    y = 150
    if step:
        text(s, 80, 120, 200, 180, step, 150, GREEN, HEAD, True, spacing=0.9); y = 320
    has_img = rel or photo_rel
    th_ = (p.H - 160 - img_h - 40) - y if has_img else p.H - 260 - y
    words(s, t, 80, y, p.W - 160, th_, INK, anchor="t" if has_img else "m")
    if photo_rel is not None:
        photo(s, photo_rel, 80, p.H - 160 - img_h, p.W - 160, img_h, *focus)
    elif rel:
        art(s, rel, 80, p.H - 160 - img_h, p.W - 160, img_h)
    furniture(p, s, False, first, last, source)
    return s


def t1b(p, quote, note="", source=None, last=True, who="Dr. Elaine Ingham"):
    """Template 1B quote card on Legacy Purple: EB Garamond italic for her words, credit in Montserrat."""
    s = p.slide(PURPLE, "Template 1B quote, Legacy Purple (Dr. Elaine content). " + note)
    pt, qh = fit(quote, p.W - 160, 560, (68, 62, 56, 50, 44), GARA, False, 1.15)
    top = (p.H - (220 + qh + 180)) / 2
    text(s, 70, top, 300, 260, "“", 260, GLOW, GARA, False, spacing=0.8)
    end = words(s, quote, 80, top + 220, p.W - 160, 560, CREAM, sizes=(pt,), font=GARA, bold=False, sp=1.15, italic=True)
    rect(s, 80, end + 50, 120, 4, GLOW)
    text(s, 80, end + 80, p.W - 160, 44, who, 30, CREAM, HEAD, True)
    text(s, 80, end + 128, p.W - 160, 40, "How to Build Great Soil, Part 1 · Diego Footer", 22, GLOW, BODY)
    furniture(p, s, True, last=last, source=source, series=False)
    return s


def t5(p, num, t, note="", source=None, first=False, last=False, rel=None, numsize=260):
    """Template 5 big number on Deep Green."""
    s = p.slide(DARK, "Template 5 big number. " + note)
    text(s, 70, 170, p.W - 140, 360, num, numsize, GLOW, HEAD, True, spacing=0.9)
    words(s, t, 80, 560, p.W - 160, 300 if rel else 560, CREAM, sizes=(52, 48, 44, 40, 36))
    if rel: art(s, rel, 80, 880, p.W - 160, 340)
    furniture(p, s, True, first, last, source)
    return s


def li_image(name, folder, rel, note, focus=(0.5, 0.5), collage_bg=None):
    """LinkedIn 1200 x 627: one full-bleed picture, white logo 90 px wide, bottom right, 50 px from the edges."""
    p = Post(name, folder, 1200, 627)
    s = p.slide(collage_bg, "LinkedIn image, no text on the image. " + note)
    if collage_bg:
        art(s, rel, 60, 40, 1080, 547)
    else:
        photo(s, rel, 0, 0, 1200, 627, *focus)
    logo(s, 1200 - 50 - 90, 627 - 50 - 90 * 668 / 743, 90, white=True)
    return p.save()


# ---------------------------------------------------------------- posts
def pizza():
    p = Post("02-11-2026-mon-ig-plant-orders-pizza")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 12:33 and 15:03; Clarholm 1985"
    full = src("12:33", "15:03") + " " + CLARHOLM + "."
    t3(p, "Your plant ordered pizza today. 🍕", CUT + "pizza-box-root-1.png", "Cover. Collage: pizza-box-root. " + full,
       S, first=True, img_h=640)
    t3(p, "It pays with root exudates: mostly sugar, a little protein, a little carbohydrate. Dr. Elaine called them cakes "
          "and cookies.", CUT + "cupcakes-cookies-root-1.png", "Collage: cupcakes-cookies-root.", S)
    t3(p, "The recipe is the order. Each blend wakes the bacteria or fungi that make the enzymes for one nutrient: boron, "
          "molybdenum, zinc, phosphorus.", CUT + "cute-bacterium-1.png", "Library cutout: cute-bacterium-1.", S, img_h=420)
    t3(p, "Those microbes pull the nutrients off sand, silt, clay and organic matter, and store them in their own bodies.",
       CUT + "fungal-hyphae-1.png", "Library cutout: fungal-hyphae-1.", S, img_h=420)
    t3(p, "Delivery: protozoa and nematodes eat the microbes and release the extra nutrients at the root, in plant-available "
          "form.", None, "No flagellate in assets/microscopy/: placeholder until one is supplied (Wes).", S,
       photo_rel=MIC + "flagellate.jpg", img_h=520)
    t3(p, "Only the plant knows what it needs today. A soil lab report arrives two weeks later.", None, "Type only.", S)
    t1b(p, "Put the plant back in control of its own life.", "Quote at 16:32.", "How to Build Great Soil, Part 1, 16:32")
    return p.save()


def tree_roots():
    p = Post("04-11-2026-wed-ig-tree-roots-myth")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 2:54 and 3:26"
    full = src("2:54", "3:26") + " [VERIFY with Wes] Root depth also varies by species and wind exposure; Wes to confirm the wording on slide 3."
    IMG = "assets/collage/originals/tree-compaction-1.png"   # closest of three attempts; roots fan out in the band
    # 1 myth with a Glow strikethrough
    s = p.slide(DARK, "Template 2 myth-buster, Glow strikethrough. Collage: tree-compaction. " + full)
    myth = "Myth: “Tree roots grow two or three feet down, then sideways.”"
    pt, mh = fit(myth, 920, 420, (60, 56, 52))
    text(s, 80, 170, 920, mh + 20, myth, pt, CREAM, HEAD, True, spacing=1.12)
    lhp = pt * 1.3333 * 1.17 * 1.12                              # Glow strikethrough across every line
    for i in range(nlines(myth, pt, 920, HEAD, True)):
        rect(s, 76, 170 + i * lhp + lhp * 0.58, 930, 10, GLOW, alpha=90)
    art(s, IMG, 80, 640, 920, 560)
    furniture(p, s, True, first=True, source=S)
    # 2 to 5: same picture, a highlight ring moves to the part each slide talks about
    rings = [(0.5, 0.5, 0.42), (0.5, 0.66, 0.26), (0.11, 0.74, 0.22), (0.78, 0.74, 0.24)]
    lines = ["In healthy soil, brassicas, grasses, shrubs and trees root deeper and deeper.",
             "Roots that turn sideways at two or three feet usually hit a compaction layer.",
             "Water stops where soil density changes, so it pools on top of the compacted layer.",
             "Oxygen moves through water far slower than through air. That zone goes anaerobic, and anaerobic microbes make "
             "compounds that harm roots."]
    iw0, ih0 = Image.open(os.path.join(ROOT, IMG)).size if os.path.exists(os.path.join(ROOT, IMG)) else (1, 1)
    r = min(920 / iw0, 640 / ih0); iw, ih = iw0 * r, ih0 * r
    ix, iy = 80 + (920 - iw) / 2, 1350 - 160 - 640 + (640 - ih) / 2      # where art() puts the picture
    for (rx, ry, rr), t in zip(rings, lines):
        s = t3(p, t, IMG, "Same collage, highlight ring on the part this slide talks about.", S, img_h=640)
        d = rr * ih
        from lib import oval
        oval(s, ix + rx * iw - d / 2, iy + ry * ih - d / 2, d, d, None, line=GREEN, lw=8)
    t3(p, "The fix: break the compaction, add biologically complete compost, and let bacteria and fungi build pores that "
          "stay open.", CUT + "tree-deep-roots-1.png", "Collage: tree-deep-roots.", S, last=True, img_h=640)
    return p.save()


def fertilizer_li():
    return li_image("05-11-2026-thu-li-fertilizer-response", "november", MIC + "sfw-amoeba-still-wide.jpg",
                    src("16:32", "24:30") + " " + CLARHOLM + ". Photo: assets/microscopy/sfw-amoeba-still-wide.jpg, the closest "
                    "library image: amoebae among bacteria-sized particles. No library image shows fungal hyphae in the same "
                    "field; replace when one is supplied (Wes).")


def glue_tie():
    p = Post("07-11-2026-sat-ig-bacteria-glue-fungi-tie")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 4:43, 9:19 and 10:42"
    full = src("4:43", "9:19", "10:42") + " [VERIFY with Wes] The glomalin line on slide 4; some viewers questioned it."
    t3(p, "Soil crumb is built in two steps. Bacteria glue. Fungi tie.", None, "Type only. " + full, S, first=True)
    t3(p, "Step 1: bacteria make sticky glues to hold on to their food, like grabbing the dinner table when water rushes "
          "through.", CUT + "bacteria-sand-grain-1.png", "Collage: bacteria-sand-grain.", S, step="1", img_h=420)
    t3(p, "Those glues bind sand, silt, clay and organic matter into micro aggregates.", CUT + "soil-crumb-1.png",
       "Collage: soil-crumb.", S)
    t3(p, "In aerobic soil, bacterial glue is alkaline. Dr. Elaine taught that most of the glue in soil is bacterial, and "
          "fungal glomalin is a small share.", None, "Type only. [VERIFY with Wes] glomalin line.", S)
    t3(p, "Step 2: fungi grow as threads and tie micro aggregates together, like string around a bundle of small packages.",
       CUT + "fungi-tie-crumbs-1.png", "Collage: fungi-tie-crumbs.", S, step="2", img_h=420)
    t3(p, "That makes macro aggregates with big pores: air passages, plus space where water moves and stays.",
       CUT + "fungal-hyphae-1.png", "No fungal-hyphae microscopy in assets/microscopy/; the library's fungal-hyphae collage "
       "cutout stands in. Replace with a micrograph when one is supplied (Wes).", S)
    t3(p, "Aerobic fungi release organic acids at pH 5.5 to 7. Bacterial soil leans alkaline. Fungal soil leans slightly "
          "acidic.", None, "Type only.", S, last=True)
    return p.save()


def minutes_years():
    p = Post("09-11-2026-mon-ig-20-minutes-vs-2-years")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 7:06, 7:51 and 8:16"
    full = src("7:06", "7:51", "8:16") + " [VERIFY with Wes] The nematode life cycle on slide 3."
    s = p.slide(DARK, "Template 5 big number, two numbers side by side. " + full)
    text(s, 80, 400, 470, 200, "20 min", 84, GLOW, HEAD, True, spacing=0.95)
    text(s, 600, 400, 400, 200, "2 yrs", 84, CREAM, HEAD, True, spacing=0.95)
    rect(s, 565, 400, 3, 130, SAGE)
    text(s, 80, 680, 920, 120, "20 minutes vs 2 years.", 52, CREAM, HEAD, True)
    furniture(p, s, True, first=True, source=S)
    t3(p, "Some disease-causing bacteria can double every 20 minutes.", CUT + "cute-bacterium-1.png",
       "Library cutout: cute-bacterium-1.", S, img_h=480)
    t3(p, "Some beneficial nematodes reproduce once every two years, and lay one or two eggs.", MIC + "cutout-6.png",
       "Microscopy: assets/microscopy/cutout-6.png (nematode). [VERIFY with Wes] nematode life cycle.", S, img_h=520)
    t3(p, "Kill everything in a soil and the fast ones move in first. Dr. Elaine compared it to gangsters moving into a "
          "trashed city block.", "assets/collage/originals/city-block-weed-1.png", "Collage: city-block-weed.", S, img_h=520)
    t1b(p, "There is no way to kill just the bad guys.", "Quote at 7:06.", "How to Build Great Soil, Part 1, 7:06", last=False)
    t3(p, "The faster way back: inoculate with biologically complete compost, so the beneficials arrive in numbers.", None,
       "Type only.", S, last=True)
    return p.save()


def story_woodlot():
    p = Post("11-11-2026-wed-ig-story-woodlot-bacteria", w=1080, h=1920)
    full = src("26:13") + " [VERIFY with Wes] Find the Michigan State study she refers to."
    s = p.slide(CREAM, "Template 7 story, frame 1. Leave y 1100 to 1450 empty for the poll sticker (About 1,000 / Over a "
                       "million). Collage: woodlot-pasture. " + full)
    text(s, 80, 260, 920, 30, SERIES, 18, GREEN, HEAD, True, track=2)
    words(s, "“How many species of bacteria live in one Michigan woodlot?”", 80, 320, 920, 360, GREEN, sizes=(64, 58, 52))
    art(s, CUT + "woodlot-pasture-1.png", 80, 700, 920, 380)
    rect(s, 140, 1110, 800, 330, None, line=SAGE, lw=2)
    text(s, 140, 1110, 800, 330, "POLL STICKER\nAbout 1,000 / Over a million", 26, FAINT, HEAD, True, align="c", anchor="m")
    logo(s, 1080 - 80 - 110, 1500 - 110 * 668 / 743, 110, white=False)
    s = p.slide(DARK, "Template 7 story, frame 2. No bacteria-rich micrograph in assets/microscopy/: placeholder under a "
                      "Deep Green overlay at 50% until one is supplied (Wes).")
    if os.path.exists(os.path.join(ROOT, MIC + "bacteria-field.jpg")):
        photo(s, MIC + "bacteria-field.jpg", 0, 0, 1080, 1920)
    else:
        rect(s, 0, 0, 1080, 1920, "8A9182")
        text(s, 80, 1620, 920, 60, "PHOTO: bacteria-rich micrograph (Wes)", 26, CREAM, HEAD, True, align="c")
        MISSING.append("PHOTO: bacteria-rich micrograph")
    rect(s, 0, 0, 1080, 1920, DARK, alpha=50)
    end = words(s, "“Over a million. And the pasture next door has a different set.”", 80, 360, 920, 520, CREAM,
                sizes=(72, 64, 58), font=GARA, bold=False, italic=True, sp=1.15)
    words(s, "Dr. Elaine Ingham, citing Michigan State University's Center for Microbial Ecology.", 80, end + 60, 920, 200,
          GLOW, sizes=(34, 30), font=BODY, bold=False)
    text(s, 80, 1440, 700, 40, "How to Build Great Soil, Part 1 · Diego Footer · 26:13", 20, CREAM, BODY)
    logo(s, 1080 - 80 - 110, 1500 - 110 * 668 / 743, 110, white=True)
    return p.save()


def water_li():
    return li_image("12-11-2026-thu-li-soil-water-infrastructure", "november", "assets/photo/hand-soil-roots-fungi.jpg",
                    src("13:48", "14:23") + " [VERIFY with Wes] Name the desert project before the oasis line runs as fact; "
                    "until then it stays attributed to Elaine. Photo: assets/photo/hand-soil-roots-fungi.jpg (Foundation "
                    "library), a hand holding an aggregated soil crumb with roots.", focus=(0.5, 0.5))


def three_18_42():
    p = Post("14-11-2026-sat-ig-3-18-42")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 20:53, 21:50 and 24:30"
    full = src("20:53", "21:50", "24:30") + " [VERIFY with Wes] Most textbooks list 17 essential elements. The 42 stays attributed to Elaine."
    s = p.slide(DARK, "Template 5 big number: 3, 18 and 42 stacked, growing. " + full)
    text(s, 80, 170, 400, 200, "3.", 140, SAGE, HEAD, True, spacing=0.9)
    text(s, 80, 360, 600, 260, "18.", 200, CREAM, HEAD, True, spacing=0.9)
    text(s, 80, 620, 900, 380, "42.", 320, GLOW, HEAD, True, spacing=0.9)
    furniture(p, s, True, first=True, source=S)
    t5(p, "3", "1950s: plant scientists taught three essential nutrients. Nitrogen, phosphorus, potassium.", source=S)
    t5(p, "18", "By the time Dr. Elaine reached high school, the count was 18.", source=S)
    t5(p, "42", "Today, the plant physiologists she talked to count 42.", source=S)
    t3(p, "Too much of one throws off the others. Bulk sulfur, and the plant struggles to take up the rest.", None,
       "Type only.", S)
    t3(p, "Her rule: Goldilocks. Enough, and never too much. Soil life delivers the amounts the plant asks for.",
       CUT + "periodic-table-1.png", "Collage: periodic-table (a few squares in Glow).", S, last=True, img_h=520)
    return p.save()


def energy():
    p = Post("16-11-2026-mon-ig-plant-energy-budget")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 2:24 and 11:58"
    full = src("2:24", "11:58") + " [VERIFY with Wes] The 20% and 60% figures are Elaine's. Wes to add a paper if there is one."
    t3(p, "Where does a plant spend its sunlight?", None, "Type only. " + full, S, first=True)

    def plant(num, t, rel, share, note):
        s = p.slide(DARK, "Template 5 big number with a drawn energy bar (exact fill). " + note)
        text(s, 70, 150, 560, 260, num, 170, GLOW, HEAD, True, spacing=0.9)
        words(s, t, 80, 430, 540, 400, CREAM, sizes=(48, 44, 40))
        art(s, rel, 640, 160, 280, 1000)
        bx, by, bw, bh = 950, 240, 50, 860                  # vertical energy bar, filled to the share
        rect(s, bx, by, bw, bh, None, line=SAGE, lw=3)
        rect(s, bx, by + bh * (1 - share), bw, bh * share, GLOW)
        text(s, 870, by + bh + 14, 190, 36, f"{int(share * 100)}%", 26, GLOW, HEAD, True, align="c")
        furniture(p, s, True, source=S)
    plant("20%", "A weed sends about 20% of its fixed energy to its roots.", CUT + "dandelion-short-root-1.png", 0.20,
          "Collage: dandelion-short-root.")
    plant("60%", "A vegetable sends about 60% below ground.", CUT + "lettuce-long-root-1.png", 0.60, "Collage: lettuce-long-root.")
    t3(p, "About half of that leaks into the soil as exudates: food for bacteria and fungi.", CUT + "cupcakes-root-microbes-1.png",
       "Collage: cupcakes-root-microbes.", S)
    t3(p, "More energy below ground means more life at the root, deeper roots and stronger soil structure.",
       CUT + "tree-deep-roots-1.png", "Collage: tree-deep-roots (shared with the tree roots post).", S, last=True)
    return p.save()


def bake():
    p = Post("18-11-2026-wed-ig-bake-an-exudate")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 12:33 and 13:11"
    full = src("12:33", "13:11")
    items = [("Dr. Elaine's challenge: go to your kitchen and bake me an exudate. 🧁", "mixing-bowl-root", True),
             ("Mostly sugar. White sugar, brown sugar, honey, syrup, molasses.", "sugar-jars", False),
             ("A little protein. Milk, eggs.", "eggs-milk", False),
             ("A little carbohydrate. Flour.", "flour-sack", False),
             ("Brown, complex sugars lean fungal. White sugar leans bacterial. The recipe decides who comes to eat.", None, False),
             ("Roots bake many recipes at once, each one for the microbes doing a job the plant needs done.",
              "cupcakes-root-microbes", False)]
    for i, (t, key, first) in enumerate(items):
        s = t3(p, t, CUT + key + "-1.png" if key else None, "Template 3, styled like a recipe card." +
               (" " + full if first else "") + (f" Collage: {key}." if key else " Type only."), S,
               first=first, last=i == len(items) - 1, img_h=560)
        rect(s, 50, 50, 980, 1250, None, line=TAN, lw=3)          # recipe card border
        rect(s, 80, 116, 120, 4, TAN)
    return p.save()


def biochar_li():
    return li_image("19-11-2026-thu-li-biochar-organic", "november", CUT + "biochar-compost-1.png",
                    src("1:28") + " [VERIFY with Wes] Confirm SFW's recommended way to charge biochar before the last paragraph "
                    "runs. Library: Boubacar's biochar stills are 360 px wide, too small for 1200 x 627, so a cut-paper collage "
                    "of biochar beside compost is used (biochar-compost).", collage_bg=CREAM)


def reel_oxygen():
    p = Post("21-11-2026-sat-ig-reel-oxygen-gauge", w=1080, h=1920)
    full = (src("19:28") + " Ingham, Soil Biology Primer, USDA NRCS: https://scholar.google.com/scholar?q=Ingham+Soil+Biology+"
            "Primer+USDA+NRCS. Library footage and stills: amoeba: assets/video/sfw-amoeba-*.mp4, assets/gif/amoeba-*.gif, "
            "assets/microscopy/sfw-amoeba-still-*.jpg, amoeba-poster-1 to 3.jpg, cutout-2.png; testate amoeba: cutout-1.png, "
            "testate-amoeba-encysting-40x-*.jpg; ciliate: cutout-3.png, cutout-4.png (stalked ciliates); flagellate: none in "
            "the library (Wes).")
    s = p.slide(DARK, "Template 6 reel cover. Collage: flagellate-ciliate. " + full)
    text(s, 80, 260, 920, 30, SERIES, 18, GLOW, HEAD, True, track=2)
    text(s, 80, 320, 920, 260, "The oxygen gauge", 96, CREAM, HEAD, True, spacing=1.0)
    art(s, CUT + "flagellate-ciliate-1.png", 80, 680, 920, 780)
    logo(s, 1080 - 80 - 110, 1500 - 110 * 668 / 743, 110, white=True)
    for i, t in enumerate(["“Is your compost running out of oxygen?”", "“Flagellates and amoebae: oxygen is fine.”",
                           "“Ciliates waking up: oxygen is dropping.”", "“More ciliates than flagellates? Turn the pile.”"], 1):
        s = p.slide(DARK if PREVIEW else None, f"Template 6 caption card {i}: 64 pt Montserrat Bold Cream, Deep Green outline, no background "
                          "(export as PNG with transparency and lay over the footage).")
        words(s, t, 80, 250, 920, 1250, CREAM, sizes=(64,), anchor="m")
        for sh in s.shapes:
            for para in sh.text_frame.paragraphs:
                for r in para.runs:
                    from lxml import etree
                    from lib import A
                    ln = etree.Element("{%s}ln" % A, w=str(int(6 * PX)))
                    sf = etree.SubElement(ln, "{%s}solidFill" % A); etree.SubElement(sf, "{%s}srgbClr" % A, val=DARK)
                    r._r.get_or_add_rPr().insert(0, ln)
    return p.save()


def microscope():
    p = Post("23-11-2026-mon-ig-microscope-question")
    S = "Dr. Elaine Ingham, How to Build Great Soil, Part 1, 28:46; school.soilfoodweb.com"
    full = src("28:46") + " Course pages: https://school.soilfoodweb.com"
    t3(p, "1.1 million people watched Dr. Elaine's soil masterclass. The question they ask most: which microscope?", None,
       "Photo: assets/photo/cy-classes-4.jpg (Foundation library), a class at microscopes; swap for a closer workshop photo "
       "of a student at a microscope if there is one. " + full, S, first=True, photo_rel="assets/photo/cy-classes-4.jpg",
       img_h=600, focus=(0.5, 0.42))
    t3(p, "At 29:03 she recommends a $350 microscope with objectives as good as Zeiss and a built-in camera.", None,
       "Type only.", S)
    s = t3(p, "What to look for today: [COPY: Wes].", None, "PHOTO placeholder: recommended microscope (from Wes).", S,
           photo_rel="Recommended microscope (from Wes)", img_h=560)
    s = p.slide(CREAM, "Template 3: 2 x 3 grid of organisms, each labelled in 22 pt Source Sans 3. Bacteria, fungal hyphae "
                       "and flagellate are not in assets/microscopy/: placeholders until supplied (Wes).")
    words(s, "What you'll see: bacteria, fungal hyphae, flagellates, amoebae, ciliates and nematodes.", 80, 150, 920, 260, INK)
    tiles = [("Bacteria", None), ("Fungal hyphae", None), ("Flagellate", None), ("Amoeba", MIC + "cutout-2.png"),
             ("Ciliate", MIC + "cutout-3.png"), ("Nematode", MIC + "cutout-6.png")]
    tw, gap = (920 - 2 * 24) / 3, 24
    for i, (lab, rel) in enumerate(tiles):
        x, y = 80 + (i % 3) * (tw + gap), 450 + (i // 3) * (tw + 70)
        rect(s, x, y, tw, tw, "1E1E1E")
        if rel: art(s, rel, x + 10, y + 10, tw - 20, tw - 20)
        else:
            text(s, x, y, tw, tw, f"PHOTO:\n{lab.lower()}", 20, "BBBBBB", HEAD, True, align="c", anchor="m"); MISSING.append(lab)
        text(s, x, y + tw + 10, tw, 40, lab, 22, INK, BODY)
    furniture(p, s, False, source=S)
    t1b(p, "I can train you in one day how to use these microscopes.", "Quote at 28:52.", "How to Build Great Soil, Part 1, 28:52",
        last=False)
    t3(p, "Learn soil microscopy in the Foundation Courses. Link in bio.", CUT + "microscope-paper-1.png",
       "Library cutout: microscope-paper-1. Link in bio: https://school.soilfoodweb.com", S, last=True, img_h=520)
    return p.save()


def teach_li():
    return li_image("03-12-2026-thu-li-learn-see-teach", "december", "assets/photo/cy-classes-4.jpg",
                    src("29:19", "30:04") + " [TAG @Stephanie] Numbers for paragraph 3: students trained, countries, mentors. "
                    "Photo: assets/photo/cy-classes-4.jpg (Foundation library), a class at microscopes with a teacher "
                    "holding a binder; swap if there is a closer photo of a mentor teaching at a microscope.", focus=(0.5, 0.42))


def reel_soil_day():
    p = Post("05-12-2026-sat-ig-reel-world-soil-day", "december", 1080, 1920)
    full = (src("30:04") + " World Soil Day, FAO: https://www.fao.org/world-soil-day. [TAG @Evan] Using the 30:04 to 30:24 "
            "clip needs Diego Footer's permission. Backup: photo of Elaine from our library (used here, slow zoom).")
    s = p.slide(PURPLE, "Template 6 reel cover, Legacy Purple. Photo: assets/photo/dr-elaine-ingham-with-microscope.jpg "
                        "(Foundation library). " + full)
    photo(s, "assets/photo/dr-elaine-ingham-with-microscope.jpg", 0, 0, 1080, 1920, 0.5, 0.4)
    rect(s, 0, 1180, 1080, 740, PURPLE, alpha=85)
    text(s, 80, 1230, 920, 30, "WORLD SOIL DAY · 5 DECEMBER", 20, GLOW, HEAD, True, track=2)
    text(s, 80, 1280, 920, 200, "You've been infected", 80, CREAM, HEAD, True, spacing=1.0)
    logo(s, 1080 - 80 - 110, 1500 - 110 * 668 / 743 + 120, 110, white=True)
    cards = ["“Now that you've listened to me, you've been infected.” Dr. Elaine Ingham",
             "“You will go forth and explain this to other people.”",
             "One viewer's answer: we've been inoculated. 🦠",
             "Happy World Soil Day. Pass it on. 💜"]
    for i, t in enumerate(cards, 1):
        s = p.slide(PURPLE, f"Template 6 caption card {i}, 64 pt Montserrat Bold Cream on Legacy Purple.")
        words(s, t, 80, 250, 920, 1250, CREAM, sizes=(64,), anchor="m")
    return p.save()


POSTS = dict(pizza=pizza, tree_roots=tree_roots, fertilizer_li=fertilizer_li, glue_tie=glue_tie,
             minutes_years=minutes_years, story_woodlot=story_woodlot, water_li=water_li, three_18_42=three_18_42,
             energy=energy, bake=bake, biochar_li=biochar_li, reel_oxygen=reel_oxygen, microscope=microscope,
             teach_li=teach_li, reel_soil_day=reel_soil_day)

if __name__ == "__main__":
    for k in [a for a in sys.argv[1:] if not a.startswith("--")] or POSTS:
        POSTS[k]()
    if MISSING:
        print("PLACEHOLDERS:", sorted(set(MISSING)))
